In [1]:
import numpy as np
import pandas as pd
from scipy import stats
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
data=pd.read_csv('/content/online_shoppers_intention.csv')

In [4]:
data.head()

Administrative  Administrative_Duration  Informational  \
0               0                      0.0              0   
1               0                      0.0              0   
2               0                      0.0              0   
3               0                      0.0              0   
4               0                      0.0              0   

   Informational_Duration  ProductRelated  ProductRelated_Duration  \
0                     0.0               1                 0.000000   
1                     0.0               2                64.000000   
2                     0.0               1                 0.000000   
3                     0.0               2                 2.666667   
4                     0.0              10               627.500000   

   BounceRates  ExitRates  PageValues  SpecialDay Month  OperatingSystems  \
0         0.20       0.20         0.0         0.0   Feb                 1   
1         0.00       0.10         0.0         0.0   Feb                 2   
2         0.20       0.20         0.0         0.0   Feb                 4   
3         0.05       0.14         0.0         0.0   Feb                 3   
4         0.02       0.05         0.0         0.0   Feb                 3   

   Browser  Region  TrafficType        VisitorType  Weekend  Revenue  
0        1       1            1  Returning_Visitor    False    False  
1        2       1            2  Returning_Visitor    False    False  
2        1       9            3  Returning_Visitor    False    False  
3        2       2            4  Returning_Visitor    False    False  
4        3       1            4  Returning_Visitor     True    False

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12330 entries, 0 to 12329
Data columns (total 18 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   Administrative           12330 non-null  int64  
 1   Administrative_Duration  12330 non-null  float64
 2   Informational            12330 non-null  int64  
 3   Informational_Duration   12330 non-null  float64
 4   ProductRelated           12330 non-null  int64  
 5   ProductRelated_Duration  12330 non-null  float64
 6   BounceRates              12330 non-null  float64
 7   ExitRates                12330 non-null  float64
 8   PageValues               12330 non-null  float64
 9   SpecialDay               12330 non-null  float64
 10  Month                    12330 non-null  object 
 11  OperatingSystems         12330 non-null  int64  
 12  Browser                  12330 non-null  int64  
 13  Region                   12330 non-null  int64  
 14  TrafficType           

In [7]:
data.isnull().sum()

Administrative             0
Administrative_Duration    0
Informational              0
Informational_Duration     0
ProductRelated             0
ProductRelated_Duration    0
BounceRates                0
ExitRates                  0
PageValues                 0
SpecialDay                 0
Month                      0
OperatingSystems           0
Browser                    0
Region                     0
TrafficType                0
VisitorType                0
Weekend                    0
Revenue                    0
dtype: int64

In [11]:
# plt.plot(data)

In [9]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [22]:
#hot encoding of non numerial values to numercial values

data = pd.get_dummies(data, columns=['Month'], drop_first=True)

data['VisitorType'] = data['VisitorType'].map({'Returning_Visitor': 1, 'New_Visitor': 0})

data['Weekend'] = data['Weekend'].astype(int)


data['Revenue'] = data['Revenue'].astype(int)



In [70]:
newdata=data.head(12245)
newdata.to_csv('enrich_data_new.csv', index=False)
# data.columns
# data.describe()
# data.info()
# data.isnull().values.any()
# data.isna().values.any()

In [32]:

data= data.dropna()


In [33]:
X = data[['Administrative', 'Administrative_Duration', 'Informational',
       'Informational_Duration', 'ProductRelated', 'ProductRelated_Duration',
       'BounceRates', 'ExitRates', 'PageValues','Month_Dec'	,'Month_Feb',	'Month_Jul','Month_June','Month_Mar',	'Month_May','Month_Nov','Month_Oct','Month_Sep','VisitorType','Weekend']]
y = data['Revenue']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [34]:
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)


In [35]:
rf_model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [36]:
y_pred = rf_model.predict(X_test)


In [37]:
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.2f}")

Accuracy: 0.90


In [39]:
print("Classification Report:\n", classification_report(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

Classification Report:
               precision    recall  f1-score   support

           0       0.93      0.95      0.94      2065
           1       0.70      0.59      0.64       384

    accuracy                           0.90      2449
   macro avg       0.81      0.77      0.79      2449
weighted avg       0.89      0.90      0.89      2449

Confusion Matrix:
 [[1967   98]
 [ 159  225]]


In [40]:
data.shape

(12245, 26)

In [41]:
y_pred = rf_model.predict(X_train)

In [42]:
accuracy = accuracy_score(y_train, y_pred)
print(f"Accuracy: {accuracy:.2f}")

Accuracy: 1.00


In [44]:
print("Classification Report:\n", classification_report(y_train, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_train, y_pred))

Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00      8288
           1       1.00      1.00      1.00      1508

    accuracy                           1.00      9796
   macro avg       1.00      1.00      1.00      9796
weighted avg       1.00      1.00      1.00      9796

Confusion Matrix:
 [[8288    0]
 [   3 1505]]


In [46]:
from sklearn.model_selection import GridSearchCV,RandomizedSearchCV

In [48]:
param_grid = {

    'n_estimators': [25, 50, 100, 150],

    'max_features': ['sqrt', 'log2', None],

    'max_depth': [3, 6, 9],

    'max_leaf_nodes': [3, 6, 9]
}

In [49]:
grid_search = GridSearchCV(RandomForestClassifier(),

                           param_grid=param_grid)
grid_search.fit(X_train, y_train)

print(grid_search.best_estimator_)

RandomForestClassifier(max_depth=6, max_features=None, max_leaf_nodes=9,
                       n_estimators=50)


In [50]:
model=RandomForestClassifier(max_depth=6, max_features=None, max_leaf_nodes=9,
                       n_estimators=50)

In [51]:
model.fit(X_train,y_train)

RandomForestClassifier(max_depth=6, max_features=None, max_leaf_nodes=9,
                       n_estimators=50)

In [52]:
pred=model.predict(X_train)
ypred=model.predict(X_test)
print(accuracy_score(y_train,pred))
print(accuracy_score(y_test,ypred))

0.9080236831359738
0.8922008983258473


In [71]:
data.shape[0]

12245

descison tree

In [72]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [73]:
X=data[['Administrative', 'Administrative_Duration', 'Informational',
       'Informational_Duration', 'ProductRelated', 'ProductRelated_Duration',
       'BounceRates', 'ExitRates', 'PageValues','Month_Dec'	,'Month_Feb',	'Month_Jul','Month_June','Month_Mar',	'Month_May','Month_Nov','Month_Oct','Month_Sep','VisitorType','Weekend']]

y=data['Revenue']


In [74]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [75]:

logreg_model = LogisticRegression(random_state=42)

#model on the training data
logreg_model.fit(X_train, y_train)


/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(random_state=42)

In [76]:

y_pred = logreg_model.predict(X_test)


In [77]:
# accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.2f}")

# Display metrics
print("Classification Report:\n", classification_report(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))


Accuracy: 0.88
Classification Report:
               precision    recall  f1-score   support

           0       0.89      0.97      0.93      2065
           1       0.72      0.35      0.47       384

    accuracy                           0.88      2449
   macro avg       0.80      0.66      0.70      2449
weighted avg       0.86      0.88      0.86      2449

Confusion Matrix:
 [[2012   53]
 [ 249  135]]


SVM

In [78]:
from sklearn.svm import SVC

In [80]:
Z=data[['Administrative', 'Administrative_Duration', 'Informational',
       'Informational_Duration', 'ProductRelated', 'ProductRelated_Duration',
       'BounceRates', 'ExitRates', 'PageValues','Month_Dec'	,'Month_Feb',	'Month_Jul','Month_June','Month_Mar',	'Month_May','Month_Nov','Month_Oct','Month_Sep','VisitorType','Weekend']]

m=data['Revenue']


In [81]:
Z_train, Z_test, m_train, m_test = train_test_split(Z,m, test_size=0.2, random_state=42)


In [82]:
from sklearn.tree import DecisionTreeClassifier

In [83]:
tree_model = DecisionTreeClassifier()

In [84]:
#data fitting
tree_model.fit(Z_train,m_train)

DecisionTreeClassifier()

In [85]:
from sklearn.tree import plot_tree

In [88]:
plt.figure(figsize=(15,10))

<Figure size 1500x1000 with 0 Axes>

<Figure size 1500x1000 with 0 Axes>

In [94]:
# tree_plot(tree_model,filled=True)

In [90]:
m_pred = tree_model.predict(Z_test)

In [91]:
m_pred

array([0, 0, 0, ..., 0, 0, 0])

In [92]:
score = accuracy_score(m_pred,m_test)


In [93]:
score

0.8399346672111065

In [95]:
print("Classification Report:\n", classification_report(m_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(m_test, y_pred))

Classification Report:
               precision    recall  f1-score   support

           0       0.89      0.97      0.93      2065
           1       0.72      0.35      0.47       384

    accuracy                           0.88      2449
   macro avg       0.80      0.66      0.70      2449
weighted avg       0.86      0.88      0.86      2449

Confusion Matrix:
 [[2012   53]
 [ 249  135]]
