In [5]:
{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "9608ba89-5973-4a99-9282-38eeb0760400",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[1 2 3]\n",
      "(3, 1)\n",
      "[[2 3 4]\n",
      " [3 4 5]\n",
      " [4 5 6]]\n"
     ]
    }
   ],
   "source": [
    "import numpy as np\n",
    "\n",
    "var1 = np.array([1,2,3])\n",
    "print(var1)\n",
    "\n",
    "var2 = np.array([[1],[2],[3]])\n",
    "print(var2.shape)\n",
    "\n",
    "print(var1 + var2)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "e1fd8fb1-36a5-4b66-91f3-81e76229390f",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "(2, 1)\n",
      "[[2 3 4]\n",
      " [3 4 5]]\n"
     ]
    }
   ],
   "source": [
    "x = np.array([[1],[2]])\n",
    "print(x.shape)\n",
    "y =np.array([[1,2,3],[1,2,3]])\n",
    "print(x+y)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "id": "f9d3501c-f7ef-45e5-a327-8b4b3f6d5f32",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[0 1 2 3 4 5 6 7 8 9]\n",
      "[500 500 500 500 500   5   6   7   8   9]\n"
     ]
    }
   ],
   "source": [
    "\n",
    "arr = np.arange(0,10)\n",
    "print(arr)\n",
    "arr[0:5] = 500\n",
    "print(arr)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 29,
   "id": "f04a9069-c2bc-4116-9374-aa25a66642f3",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[[1. 1. 1. 1.]\n",
      " [1. 1. 1. 1.]\n",
      " [1. 1. 1. 1.]\n",
      " [1. 1. 1. 1.]]\n",
      "[[300. 300. 300. 300.]\n",
      " [  1.   1.   1.   1.]\n",
      " [  1.   1.   1.   1.]\n",
      " [  1.   1.   1.   1.]]\n"
     ]
    }
   ],
   "source": [
    "#on 2d array\n",
    "array2 = np.ones((4,4))\n",
    "print(array2)\n",
    "array2[-4]= 300# or [0] acc to indexing from positive to negative or reverse\n",
    "print(array2)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 31,
   "id": "ff671c33-986b-4ebd-ba6a-b4b5cd388518",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[[300. 301. 302. 303.]\n",
      " [  1.   2.   3.   4.]\n",
      " [  1.   2.   3.   4.]\n",
      " [  1.   2.   3.   4.]]\n"
     ]
    }
   ],
   "source": [
    "print(array2 + np.arange(0,4))"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}


{'cells': [{'cell_type': 'code',
   'execution_count': 8,
   'id': '9608ba89-5973-4a99-9282-38eeb0760400',
   'metadata': {},
   'outputs': [{'name': 'stdout',
     'output_type': 'stream',
     'text': ['[1 2 3]\n',
      '(3, 1)\n',
      '[[2 3 4]\n',
      ' [3 4 5]\n',
      ' [4 5 6]]\n']}],
   'source': ['import numpy as np\n',
    '\n',
    'var1 = np.array([1,2,3])\n',
    'print(var1)\n',
    '\n',
    'var2 = np.array([[1],[2],[3]])\n',
    'print(var2.shape)\n',
    '\n',
    'print(var1 + var2)']},
  {'cell_type': 'code',
   'execution_count': 11,
   'id': 'e1fd8fb1-36a5-4b66-91f3-81e76229390f',
   'metadata': {},
   'outputs': [{'name': 'stdout',
     'output_type': 'stream',
     'text': ['(2, 1)\n', '[[2 3 4]\n', ' [3 4 5]]\n']}],
   'source': ['x = np.array([[1],[2]])\n',
    'print(x.shape)\n',
    'y =np.array([[1,2,3],[1,2,3]])\n',
    'print(x+y)']},
  {'cell_type': 'code',
   'execution_count': 18,
   'id': 'f9d3501c-f7ef-45e5-a327-8b4b3f6d5f32',
   'metadata': {}

In [6]:
# arr1 = np.arange(0,5)
arr2 = np.arange(0,5)

# print("1st arr:-",arr1)
print("2nd arr:-",arr2)

#addition
print("sum of arrays will be:- ",(8+arr2))
#subtraction
print("sub of arrays will be:- ",(8-arr2))
#division
print("div of arrays will be:- ",(arr2/8))
#multiplication
print("mul of arrays will be:- ",(8*arr2))
#powerr of elements
print("power of arrays will be:- ",(8**arr2))


NameError: name 'np' is not defined

In [ ]:
# arr1 = np.arange(0,5)
arr2 = np.arange(0,5)

# print("1st arr:-",arr1)
print("2nd arr:-",arr2)

#addition
print("sum of arrays will be:- ",(8+arr2))
#subtraction
print("sub of arrays will be:- ",(8-arr2))
#division
print("div of arrays will be:- ",(arr2/8))
#multiplication
print("mul of arrays will be:- ",(8*arr2))
#powerr of elements
print("power of arrays will be:- ",(8**arr2))
#sqrt
print("square_root of array will be:- ",np.sqrt(arr2))
#max and min()
print("max-value of array will be:- ",np.max(arr2))
print("min_value of array will be:- ",np.min(arr2))
#exponential of elements
print("expo of array will be:- ",np.exp(arr2))
#size
print("size of array will be:- ",np.size(arr2))
#sin,cos,tan etc
print("trigonometry of array will be:- ",np.sin(arr2))
#


2nd arr:- [0 1 2 3 4]
sum of arrays will be:-  [ 8  9 10 11 12]
sub of arrays will be:-  [8 7 6 5 4]
div of arrays will be:-  [0.    0.125 0.25  0.375 0.5  ]
mul of arrays will be:-  [ 0  8 16 24 32]
power of arrays will be:-  [   1    8   64  512 4096]
square_root of array will be:-  [0.         1.         1.41421356 1.73205081 2.        ]
max-value of array will be:-  4
min_value of array will be:-  0
square_root of array will be:-  [ 1.          2.71828183  7.3890561  20.08553692 54.59815003]
size of array will be:-  5
square_root of array will be:-  [ 0.          0.84147098  0.90929743  0.14112001 -0.7568025 ]
