In [8]:
import numpy as np

var1 = np.array([1,2,3])
print(var1)

var2 = np.array([[1],[2],[3]])
print(var2.shape)

print(var1 + var2)

[1 2 3]
(3, 1)
[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [11]:
x = np.array([[1],[2]])
print(x.shape)
y =np.array([[1,2,3],[1,2,3]])
print(x+y)

(2, 1)
[[2 3 4]
 [3 4 5]]


In [18]:

arr = np.arange(0,10)
print(arr)
arr[0:5] = 500
print(arr)

[0 1 2 3 4 5 6 7 8 9]
[500 500 500 500 500   5   6   7   8   9]


In [29]:
#on 2d array
array2 = np.ones((4,4))
print(array2)
array2[-4]= 300# or [0] acc to indexing from positive to negative or reverse
print(array2)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[300. 300. 300. 300.]
 [  1.   1.   1.   1.]
 [  1.   1.   1.   1.]
 [  1.   1.   1.   1.]]


In [31]:
print(array2 + np.arange(0,4))

[[300. 301. 302. 303.]
 [  1.   2.   3.   4.]
 [  1.   2.   3.   4.]
 [  1.   2.   3.   4.]]
