In [4]:
#1st answer
import numpy as np
vector1 = np.arange(25)
v_convert= vector1.reshape(5,5)
print(v_convert + 100)


[[100 101 102 103 104]
 [105 106 107 108 109]
 [110 111 112 113 114]
 [115 116 117 118 119]
 [120 121 122 123 124]]
