In [15]:
import numpy as np
a= [1,2,3,4,5,6]
y = np.array(a)
print(y)
print(type(y))
print(y.ndim)

[1 2 3 4 5 6]
<class 'numpy.ndarray'>
1


In [11]:
l = []
for i in range(1,5):
    int_1 = int(input("enter number: "))
    l.append(int_1)

print(np.array(l))
    

enter number:  3
enter number:  5
enter number:  5
enter number:  6


[3 5 5 6]


In [16]:
import numpy as np
l = [[1,2,3],[4,5,6],[7,8,9]]
# print(l)
matrix_new = np.array(l)
print(matrix_new)
print(matrix_new.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2


In [17]:
import numpy as np
list2 = np.array([[[1,2,3],[1,5,7],[6,4,9]]])
print(list2.ndim)

3


In [54]:
#arrange
import numpy as np
print(np.arange(1,20,2))
#end

[ 1  3  5  7  9 11 13 15 17 19]


In [26]:
#arange with dtype
import numpy as np
print(np.arange(1,20,3, dtype=float))
print(ll)

[ 1.  4.  7. 10. 13. 16. 19.]
[1 2 3 4 5]


In [31]:
#zeroes method
import numpy as np
print(np.zeros(3))
print(np.zeros((4,6)) )

[0. 0. 0.]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [56]:
#eye method
print(np.eye(8))

[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]


In [60]:
#rand method
import numpy as np
print(np.random.rand(4))

[0.40998447 0.12243974 0.07366473 0.86942891]


In [64]:
#randint()
import numpy as np
print(np.random.randint(1,100))
print(np.random.randint(1,100,29))

54
[98 19 84 40 10 41 65 43 44 96 15  5 31 18 84 13 72 11 89 62 39 32 79 38
 26 81 58 49 62]


In [80]:
#using arnge and randint()
import numpy as np
ar_ar = np.arange(16)
ar_rint = np.random.randint(0,100,10)
zer = np.eye(6)
print(zer)
print(ar_ar)
print(ar_rint)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[16 94 15 25  0 49 33 38 30 30]


In [81]:
#reshape
print(ar_ar.reshape(4,4))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [83]:
#min and max()
import numpy as np
print(ar_ar.min())
print(ar_ar.max())

0
15


In [86]:
#argmax and argmin()
import numpy as np
arg = np.arange(16)
arg_1 = np.random.randint(0,100,10)

print(arg.min())
print(arg.argmax())
print(arg.argmin())


0
15
0


In [88]:
#size,shape and type of array
print(arg.shape)
print(arg.dtype)
print(arg.size)

(16,)
int32
16
