In [9]:
import pandas as pd
import numpy as np

ind = 'r1 r2 r3 r4 r5 r6 r7 r8 r9 r10'.split()
col =  'c1 c2 c3 c4 c5 c6 c7 c8 c8 c10'.split()
print(ind)

arr2d = np.arange(0,100)
print(arr2d)
reshap = arr2d.reshape(10,10)
print(reshap)

['r1', 'r2', 'r3', 'r4', 'r5', 'r6', 'r7', 'r8', 'r9', 'r10']
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [33]:
#using data+frame methods

dfe = pd.DataFrame(data=reshap,index=ind,columns =col)
print(dfe)

     c1  c2  c3  c4  c5  c6  c7  c8  c8  c10
r1    0   1   2   3   4   5   6   7   8    9
r2   10  11  12  13  14  15  16  17  18   19
r3   20  21  22  23  24  25  26  27  28   29
r4   30  31  32  33  34  35  36  37  38   39
r5   40  41  42  43  44  45  46  47  48   49
r6   50  51  52  53  54  55  56  57  58   59
r7   60  61  62  63  64  65  66  67  68   69
r8   70  71  72  73  74  75  76  77  78   79
r9   80  81  82  83  84  85  86  87  88   89
r10  90  91  92  93  94  95  96  97  98   99


In [32]:
#fetching columns
print(dfe[["c1","c3"]])
#second approach method
print(dfe.c7)

     c1  c3
r1    0   2
r2   10  12
r3   20  22
r4   30  32
r5   40  42
r6   50  52
r7   60  62
r8   70  72
r9   80  82
r10  90  92
r1      6
r2     16
r3     26
r4     36
r5     46
r6     56
r7     66
r8     76
r9     86
r10    96
Name: c7, dtype: int32


In [38]:
dfe.drop(["c8"],axis =1,inplace= True)
print(dfe)

KeyError: "['c8'] not found in axis"

In [35]:
print(pd.DataFrame(data=reshap,index=ind,columns=col))

     c1  c2  c3  c4  c5  c6  c7  c8  c8  c10
r1    0   1   2   3   4   5   6   7   8    9
r2   10  11  12  13  14  15  16  17  18   19
r3   20  21  22  23  24  25  26  27  28   29
r4   30  31  32  33  34  35  36  37  38   39
r5   40  41  42  43  44  45  46  47  48   49
r6   50  51  52  53  54  55  56  57  58   59
r7   60  61  62  63  64  65  66  67  68   69
r8   70  71  72  73  74  75  76  77  78   79
r9   80  81  82  83  84  85  86  87  88   89
r10  90  91  92  93  94  95  96  97  98   99


In [41]:
# dfe['c11'] = dfe['c9'] + dfe['c10']
# print(dfe)

In [44]:
print(dfe.loc[['r2','r3']])

    c1  c2  c3  c4  c5  c6  c7  c10
r2  10  11  12  13  14  15  16   19
r3  20  21  22  23  24  25  26   29


In [47]:
print(dfe.iloc[[1,2]])
print("Subset \n",dfe.loc[['r1','r2'],['c1','c2']])

    c1  c2  c3  c4  c5  c6  c7  c10
r2  10  11  12  13  14  15  16   19
r3  20  21  22  23  24  25  26   29
Subset 
     c1  c2
r1   0   1
r2  10  11
